# Generated by Django 4.2.2 on 2023-06-14 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Status',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status_en', models.CharField(max_length=100, unique=True)),
                ('status_ar', models.CharField(max_length=100, unique=True)),
                ('blacklist_from_applications', models.BooleanField(default=False)),
                ('active_employee', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annual_Leave_Type',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('annual_leave_type_en', models.CharField(max_length=100, unique=True)),
                ('annual_leave_type_ar', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_status',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Attendance_status_en', models.CharField(max_length=100, unique=True)),
                ('Attendance_status_ar', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('city_name_en', models.CharField(max_length=100, unique=True)),
                ('city_name_ar', models.CharField(max_length=100, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country_name_en', models.CharField(max_length=100, unique=True)),
                ('country_name_ar', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('district_name_en', models.CharField(max_length=100, unique=True)),
                ('district_name_ar', models.CharField(max_length=100, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.citie')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gender_en', models.CharField(max_length=50, unique=True)),
                ('gender_ar', models.CharField(max_length=50, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hierarcie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hierarcy_name_en', models.CharField(max_length=100, unique=True)),
                ('hierarcy_name_ar', models.CharField(max_length=100, unique=True)),
                ('hierarcy_number', models.IntegerField(unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('institute_en', models.CharField(max_length=100, unique=True)),
                ('institute_ar', models.CharField(max_length=100, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Types',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('interview_type_en', models.CharField(max_length=100, unique=True)),
                ('interview_type_ar', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobtitle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('jobtitle_en', models.CharField(max_length=100, unique=True)),
                ('jobtitle_ar', models.CharField(max_length=100, unique=True)),
                ('max_employees', models.IntegerField()),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MartialStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('martial_status_en', models.CharField(max_length=50, unique=True)),
                ('martial_status_ar', models.CharField(max_length=50, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('military_status_en', models.CharField(max_length=50, unique=True)),
                ('military_status_ar', models.CharField(max_length=50, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Number_Type',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mobile_Number_Type_en', models.CharField(max_length=100, unique=True)),
                ('mobile_Number_Type_ar', models.CharField(max_length=100, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='National_ID_Type',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('national_ID_type_en', models.CharField(max_length=100, unique=True)),
                ('national_ID_type_ar', models.CharField(max_length=100, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalitie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nationality_en', models.CharField(max_length=50)),
                ('nationality_ar', models.CharField(max_length=50)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('qualification_en', models.CharField(max_length=100, unique=True)),
                ('qualification_ar', models.CharField(max_length=100, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('religion_en', models.CharField(max_length=50, unique=True)),
                ('religion_ar', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weekdays',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('weekday_en', models.CharField(max_length=100, unique=True)),
                ('weekday_ar', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('region_name_en', models.CharField(max_length=100, unique=True)),
                ('region_name_ar', models.CharField(max_length=100, unique=True)),
                ('collect_cvs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.district')),
            ],
        ),
        migrations.AddField(
            model_name='citie',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.countrie'),
        ),
    ]
