# Generated by Django 4.2.2 on 2023-06-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annual_Leave_Type',
            new_name='AnnualLeaveType',
        ),
        migrations.RenameModel(
            old_name='Attendance_status',
            new_name='AttendanceStatus',
        ),
        migrations.RenameModel(
            old_name='Activity_Status',
            new_name='EmployeeActivityStatus',
        ),
        migrations.RenameModel(
            old_name='Interview_Types',
            new_name='InterviewTypes',
        ),
        migrations.RenameModel(
            old_name='Mobile_Number_Type',
            new_name='MobileNumberType',
        ),
        migrations.RenameModel(
            old_name='National_ID_Type',
            new_name='NationalIDType',
        ),
        migrations.DeleteModel(
            name='Weekdays',
        ),
    ]
