# Generated by Django 4.2.2 on 2023-06-17 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0006_remove_notificationchannel_channel_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketChannels',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification_channels', models.ManyToManyField(related_name='AssignedUsers', to='notifications.notificationchannel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='WebsocketChannels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
