# Generated by Django 4.2.2 on 2023-06-17 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0006_remove_notificationchannel_channel_users'),
        ('websocketcore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsocketChannels',
            new_name='WebsocketChannel',
        ),
    ]
