# Generated by Django 4.2.2 on 2023-06-17 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='channel_users',
            field=models.ManyToManyField(related_name='NotificationChannels', to=settings.AUTH_USER_MODEL),
        ),
    ]
