# Generated by Django 4.2.2 on 2023-06-17 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_notificationchannel_channel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_user',
            field=models.ManyToManyField(related_name='ReadNotifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
