# Generated by Django 4.2.2 on 2023-06-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_is_read_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationchannel',
            name='channel_users',
        ),
    ]
